### ISSUE TITLE
Add paginate-links style

### ISSUE THREAD

**Issue by lipecss** [TahaSh/vue-paginate#129]
I'm trying to add style to pagination-links but it doesn't work at all. Only be able to change the

```css
ul.paginate-links {
  display: inline-flex;
  list-style-type: none;
}
```

But I want to adjust it, put a hover, change the font size, and the documentation doesn't explain it right. I followed Jsfiddle but I didn't understand how you gave the style.
