### ISSUE TITLE
Is possible resume the paginate numbers?

### ISSUE THREAD

**Issue by juulhao** [TahaSh/vue-paginate#97]
I would like list my pagination like this
For example: (1),(2),..., (18)
Exist an property for this?
Any one can help me?

**Comment by juulhao** [comment]
@TahaSh @callumacrae @extend1994 @deohnas Guys, can you help me?

**Comment by TahaSh** [comment]
@juulhao unfortunately, this package doesn't support formatting pagination links yet. But it should be supported soon.

However, you can accomplish the same using css.
``` css
.paginate-links li.number a:before {
  content: '('
}
.paginate-links li.number a:after {
  content: ')'
}
```
